spring.application.name=declarative-http-client

external.retry.max-attempts=3
external.retry.delay-millis=1000

# AuthService \u7CFB\u7EDF\u81EA\u5B9A\u7FA9 Header
external.systems.auth.auth-type=JWT
external.systems.auth.base-url=http://localhost:8088
external.systems.auth.enable-business-error-handling=true
external.systems.auth.headers.X-Client-Id=my-client
external.systems.auth.headers.X-Env=dev

logging.level.com.example.demo=DEBUG
logging.level.feign.Logger=DEBUG

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true

# \u89E3\u6C7A Console \u4E2D\u6587\u4E82\u78BC
logging.charset.console=UTF-8
logging.charset.file=UTF-8

# \u5E95\u5C64 HTTP \u5F15\u64CE\u5207\u63DB (REST_CLIENT \u6216 WEB_CLIENT)
external.client-type=WEB_CLIENT